
all:
  children:
    development:
      children:
        db_d_dbbds1:
          hosts:
            db_d_dbbds1_prim:
              ansible_host: 192.168.56.11
            db_d_dbbds1_repl:
              ansible_host: 192.168.56.12
        db_d_dbbds2:
          hosts:
            db_d_dbbds2_prim:
              ansible_host: 192.168.56.13
            db_d_dbbds2_repl:
              ansible_host: 192.168.56.14

    test:
      children:
        db_t_dbbds1:
          hosts:
            db_t_dbbds1_prim:
              ansible_host: 192.168.56.21
            db_t_dbbds1_repl:
              ansible_host: 192.168.56.22
        db_t_dbbds2:
          hosts:
            db_t_dbbds2_prim:
              ansible_host: 192.168.56.23
            db_t_dbbds2_repl:
              ansible_host: 192.168.56.24

    acceptance:
      children:
        db_a_dbbds1:
          hosts:
            db_a_dbbds1_prim:
              ansible_host: 192.168.56.31
            db_a_dbbds1_repl:
              ansible_host: 192.168.56.32
        db_a_dbbds2:
          hosts:
            db_a_dbbds2_prim:
              ansible_host: 192.168.56.33
            db_a_dbbds2_repl:
              ansible_host: 192.168.56.34

    production:
      children:
        db_p_dbbds1:
          hosts:
            db_p_dbbds1_prim:
              ansible_host: 192.168.56.41
            db_p_dbbds1_repl:
              ansible_host: 192.168.56.42
        db_p_dbbds2:
          hosts:
            db_p_dbbds2_prim:
              ansible_host: 192.168.56.43
            db_p_dbbds2_repl:
              ansible_host: 192.168.56.44 
