all:
  children:
    development:
      children:
        db_d_dbbds1:
          hosts:
            db_d_dbbds1_prim:
            db_d_dbbds1_repl:
        db_d_dbbds2:
          hosts:
            db_d_dbbds2_prim:
            db_d_dbbds2_repl:

    test:
      children:
        db_t_dbbds1:
          hosts:
            db_t_dbbds1_prim:
            db_t_dbbds1_repl:
        db_t_dbbds2:
          hosts:
            db_t_dbbds2_prim:
            db_t_dbbds2_repl:

    acceptance:
      children:
        db_a_dbbds1:
          hosts:
            db_a_dbbds1_prim:
            db_a_dbbds1_repl:
        db_a_dbbds2:
          hosts:
            db_a_dbbds2_prim:
            db_a_dbbds2_repl:

    production:
      children:
        db_p_dbbds1:
          hosts:
            db_p_dbbds1_prim:
            db_p_dbbds1_repl:
        db_p_dbbds2:
          hosts:
            db_p_dbbds2_prim:
            db_p_dbbds2_repl: